CREATE TABLE product (
    id BINARY(16) PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    cod_bar VARCHAR(13) NOT NULL UNIQUE,
    storage_area VARCHAR(10) NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity >= 0)
)