CREATE TABLE product (
    id BINARY(16) PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    cod_bar VARCHAR(13) NOT NULL,
    value DECIMAL(19,2) NOT NULL
);