spring.application.name=sales-java

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=none

server.port=${SERVER_PORT}

resilience4j.circuitbreaker.instances.grpc.sliding-window-size=5
resilience4j.circuitbreaker.instances.grpc.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.grpc.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.grpc.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.grpc.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.grpc.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.grpc.register-health-indicator=true

resilience4j.retry.instances.grpc.max-attempts=2
resilience4j.retry.instances.grpc.wait-duration=500ms
resilience4j.retry.instances.grpc.retry-exceptions=io.grpc.StatusRuntimeException
resilience4j.retry.instances.grpc.enable-exponential-backoff=true
resilience4j.retry.instances.grpc.exponential-backoff-multiplier=2
resilience4j.retry.instances.grpc.fail-after-max-attempts=true

resilience4j.ratelimiter.instances.grpc.limit-for-period=15
resilience4j.ratelimiter.instances.grpc.limit-refresh-period=8s
resilience4j.ratelimiter.instances.grpc.timeout-duration=0